# Generated by Django 4.1.7 on 2023-08-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_auth', '0002_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=0.0),
        ),
    ]
