# Generated by Django 4.1.7 on 2023-08-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_auth', '0003_user_altura_alter_pessoa_idade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
