# Generated by Django 4.1.7 on 2023-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_auth', '0004_delete_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
